### ISSUE TITLE
removed role is added back in again?

### ISSUE THREAD

**Issue by gebeer** [baumrock/RockMigrations#11]
In https://github.com/baumrock/RockMigrations/blob/08262b7aa165c76bdcb5686798f1960ca6b037e8/RockMigrations.module.php#L2837
The role is removed but then code execution continues and in https://github.com/baumrock/RockMigrations/blob/08262b7aa165c76bdcb5686798f1960ca6b037e8/RockMigrations.module.php#L2839 it is added again.
Or am I reading this wrong?

**Comment by BernhardBaumrock** [comment]
As far as I remember and how I'm reading it it is like this:
```
$rm->setTemplateAccess("my-tpl", "my-role", ["view"]);
$rm->setTemplateAccess("my-tpl", "my-role", ["edit"]);
// role has view + edit

$rm->setTemplateAccess("my-tpl", "my-role", ["view"]);
$rm->setTemplateAccess("my-tpl", "my-role", ["edit"], true);
// role has only edit access
```
Does that make sense?

**Comment by gebeer** [comment]
> $rm->setTemplateAccess("my-tpl", "my-role", ["view"]);
> $rm->setTemplateAccess("my-tpl", "my-role", ["edit"], true);
> // role has only edit access
You are right, this will work. But order of setTemplateAccess calls is important here and code is not very intuitive. I would read the second line as "remove edit permission for role my-role from template my-tpl where actually the edit permission gets added. Maybe the behaviour should be documented.

**Comment by BernhardBaumrock** [comment]
> But order of setTemplateAccess calls is important here and code is not very intuitive.
Well... I partly agree but I don't know of a better solution.

That's a fundamental concept of migrations and the same concept as with "fields" and "fields-". Migrations do always only ADD or OVERWRITE things by default. They do not REMOVE things unless you explicitly tell it to do that. And that's what you do with the TRUE flag as last parameter.

If it worked differently it would wipe everything that is not defined in migrations, which is obviously not what we want.

I've also thought of naming it "addTemplateAccess" but that's also not what it does. Because it does also overwrite settings if you change something. And that's the same for setTemplateData or setFieldData... That was one main improvement to RM1 where naming was not always consistent. I think RM2 is quite good in that regard.

So for me the syntax is quite clear and makes sense. But if you have a good example I'm happy to think about it :)

And of course I'm always happy to get help on the docs.

**Comment by gebeer** [comment]
Thank you for the explanation. I made a [PR](https://github.com/baumrock/RockMigrations/pull/13) with code documentation for the behaviour
