### ISSUE TITLE
Allow field parent_id to be a path + migrate method order of operation issue

### ISSUE THREAD

**Issue by jlahijani** [baumrock/RockMigrations#23]
I've written a migration module for my own internal use that's not as sophisticated as RM, but the lessons I learned apply to RM as well.  When creating fields, templates and pages, the order of operation matters since there are dependencies between them.  RM gets this right mostly, but there is technically an issue.

Keep in mind, this is within the context of using the migrate() method...

A

First, a feature request.  When creating a page field, it requires `parent_id` to actually be an ID.  It would be nice if RM could support a page path here so I could put something like `/posts/` as this would make it more portable.  Otherwise, I could put `wire('pages')->get('/posts/')->id` here instead of a hardcoded ID.  I noticed with `template_id` it doesn't actually require an ID and putting `post` works fine there.  So making `parent_id` work in a similar way would bring some consistency.

B

Regardless of whether a `parent_id` is hardcoded or provided using `wire('pages')->get('/posts/')->id`, this will not get set when running a FRESH migration.  It will require the migration to run twice.  This is because of how the `migrate()` method works in RM.  The migrate method runs things in this order (I've skipped a few steps that aren't relevant):
1. creates fields
2. creates templates
3. sets field data
4. sets template data
5. creates pages

The problem with this is that for a page reference field, the parent_id doesn't exist yet since the page it's referring to has not yet been created.  You could have a step 6 that re-does step 3 (meaning set field data twice), but that won't work either given how setting it via `wire('pages')->get('/posts/')->id` doesn't get reevaluated.

**Comment by BernhardBaumrock** [comment]
Hey @jlahijani thx.

A: I've added this to the dev branch! https://github.com/baumrock/RockMigrations/commit/e45e4306f8a77a84c1c4723f48b63320535884a1

B: There will always be situations like that when using a single migrate() method. That's why there is still the option to use the API itself so that you have control over what happens when. And that's one of the reasons why I always said that having migrations in PHP files is preferable to having them as YAML files.

In your case I'd just use one migrate() call followed by a createPage() call. That way you make sure that you first have all the fields and templates ready and after that you create the pages you need.
