### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by spinboxnl** [baumrock/RockMigrations#26]
![image](https://github.com/baumrock/RockMigrations/assets/20025981/2cff27d9-d9b0-4361-9515-ef207b31c17c)

I have updated from 2.x version to 3.27

Seems like it's trying to load a local file in admin (RockMigrations.admin.css and RockMigrations.js) instead of a relative path.

`<link type='text/css' href='D:\development\bpg-qrmetals\site\modules\RockMigrations/RockMigrations.admin.css?m=1691581368' rel='stylesheet'/>`

**Comment by BernhardBaumrock** [comment]
@spinboxnl could be a windows path issue but I need more information. Could you please help me to debug this?

I guess the issue is in RockMigrations.module.php in the method `filePath`, but I have no idea why it should return the wrong path?! Can you please do some debugging there?

For example what do you get if you put that in the tracy console?

```php
$path = $rockmigrations->filePath("D:\development\bpg-qrmetals\site\modules\RockMigrations/RockMigrations.admin.css");
db($path);
db(Paths::normalizeSeparators($path));
```
